/// Tiny built-in localization for the handful of UI strings.
/// English is the fallback. Add more keys/languages here as needed.
class Strings {
  Strings(this.code);

  final String code;

  static const supported = {
    'en': 'English',
    'te': 'తెలుగు',
    'hi': 'हिन्दी',
    'es': 'Español',
  };

  static const _values = <String, Map<String, String>>{
    'en': {
      'appName': 'Block Blast Classic',
      'tagline': 'A relaxing block puzzle',
      'start': 'Start Game',
      'statistics': 'Statistics',
      'settings': 'Settings',
      'rate': 'Rate App',
      'privacy': 'Privacy Policy',
      'score': 'Score',
      'best': 'Best',
      'gamesPlayed': 'Games Played',
      'playAgain': 'Play Again',
      'home': 'Home',
      'gameOver': 'Game Over',
      'finalScore': 'Final Score',
      'bestScore': 'Best Score',
      'rowsCleared': 'Rows Cleared',
      'colsCleared': 'Columns Cleared',
      'totalGames': 'Total Games Played',
      'highestScore': 'Highest Score',
      'averageScore': 'Average Score',
      'blocksPlaced': 'Total Blocks Placed',
      'sound': 'Sound',
      'music': 'Music',
      'vibration': 'Vibrations',
      'darkMode': 'Dark Mode',
      'highContrast': 'High Contrast',
      'colorBlind': 'Color-blind Friendly',
      'largeText': 'Large Text',
      'language': 'Language',
      'resetScore': 'Reset High Score',
      'resetConfirm': 'Reset your best score and all statistics?',
      'cancel': 'Cancel',
      'reset': 'Reset',
      'combo': 'Combo',
      'newBest': 'New Best!',
      'noAds': 'No ads. Your scores stay on your device.',
    },
    'te': {
      'appName': 'Block Blast Classic',
      'tagline': 'హాయిగా ఆడుకునే బ్లాక్ పజిల్',
      'start': 'ఆట మొదలుపెట్టు',
      'statistics': 'గణాంకాలు',
      'settings': 'సెట్టింగ్స్',
      'rate': 'రేటింగ్ ఇవ్వండి',
      'privacy': 'గోప్యతా విధానం',
      'score': 'స్కోరు',
      'best': 'అత్యుత్తమం',
      'gamesPlayed': 'ఆడిన ఆటలు',
      'playAgain': 'మళ్లీ ఆడు',
      'home': 'హోమ్',
      'gameOver': 'ఆట ముగిసింది',
      'finalScore': 'ఫైనల్ స్కోరు',
      'bestScore': 'అత్యుత్తమ స్కోరు',
      'rowsCleared': 'క్లియర్ చేసిన వరుసలు',
      'colsCleared': 'క్లియర్ చేసిన నిలువు వరుసలు',
      'totalGames': 'మొత్తం ఆటలు',
      'highestScore': 'అత్యధిక స్కోరు',
      'averageScore': 'సగటు స్కోరు',
      'blocksPlaced': 'పెట్టిన బ్లాకులు',
      'sound': 'సౌండ్',
      'music': 'మ్యూజిక్',
      'vibration': 'వైబ్రేషన్',
      'darkMode': 'డార్క్ మోడ్',
      'highContrast': 'హై కాంట్రాస్ట్',
      'colorBlind': 'కలర్-బ్లైండ్ మోడ్',
      'largeText': 'పెద్ద అక్షరాలు',
      'language': 'భాష',
      'resetScore': 'హై స్కోరు రీసెట్',
      'resetConfirm': 'మీ అత్యుత్తమ స్కోరు, గణాంకాలు తొలగించాలా?',
      'cancel': 'రద్దు',
      'reset': 'రీసెట్',
      'combo': 'కాంబో',
      'newBest': 'కొత్త రికార్డ్!',
      'noAds': 'యాడ్స్ లేవు. మీ స్కోర్లు మీ ఫోన్లోనే ఉంటాయి.',
    },
    'hi': {
      'appName': 'Block Blast Classic',
      'tagline': 'एक आरामदायक ब्लॉक पहेली',
      'start': 'खेल शुरू करें',
      'statistics': 'आँकड़े',
      'settings': 'सेटिंग्स',
      'rate': 'ऐप रेट करें',
      'privacy': 'गोपनीयता नीति',
      'score': 'स्कोर',
      'best': 'सर्वश्रेष्ठ',
      'gamesPlayed': 'खेले गए खेल',
      'playAgain': 'फिर से खेलें',
      'home': 'होम',
      'gameOver': 'खेल समाप्त',
      'finalScore': 'अंतिम स्कोर',
      'bestScore': 'सर्वश्रेष्ठ स्कोर',
      'rowsCleared': 'साफ़ की गई पंक्तियाँ',
      'colsCleared': 'साफ़ किए गए स्तंभ',
      'totalGames': 'कुल खेले गए खेल',
      'highestScore': 'उच्चतम स्कोर',
      'averageScore': 'औसत स्कोर',
      'blocksPlaced': 'रखे गए ब्लॉक',
      'sound': 'ध्वनि',
      'music': 'संगीत',
      'vibration': 'कंपन',
      'darkMode': 'डार्क मोड',
      'highContrast': 'हाई कंट्रास्ट',
      'colorBlind': 'कलर-ब्लाइंड मोड',
      'largeText': 'बड़ा टेक्स्ट',
      'language': 'भाषा',
      'resetScore': 'हाई स्कोर रीसेट करें',
      'resetConfirm': 'अपना सर्वश्रेष्ठ स्कोर और आँकड़े मिटाएँ?',
      'cancel': 'रद्द करें',
      'reset': 'रीसेट',
      'combo': 'कॉम्बो',
      'newBest': 'नया रिकॉर्ड!',
      'noAds': 'कोई विज्ञापन नहीं। आपके स्कोर आपके डिवाइस पर रहते हैं।',
    },
    'es': {
      'appName': 'Block Blast Classic',
      'tagline': 'Un relajante puzzle de bloques',
      'start': 'Jugar',
      'statistics': 'Estadísticas',
      'settings': 'Ajustes',
      'rate': 'Calificar app',
      'privacy': 'Política de privacidad',
      'score': 'Puntos',
      'best': 'Récord',
      'gamesPlayed': 'Partidas',
      'playAgain': 'Jugar de nuevo',
      'home': 'Inicio',
      'gameOver': 'Fin del juego',
      'finalScore': 'Puntuación final',
      'bestScore': 'Récord',
      'rowsCleared': 'Filas eliminadas',
      'colsCleared': 'Columnas eliminadas',
      'totalGames': 'Partidas totales',
      'highestScore': 'Puntuación máxima',
      'averageScore': 'Puntuación media',
      'blocksPlaced': 'Bloques colocados',
      'sound': 'Sonido',
      'music': 'Música',
      'vibration': 'Vibración',
      'darkMode': 'Modo oscuro',
      'highContrast': 'Alto contraste',
      'colorBlind': 'Modo daltónico',
      'largeText': 'Texto grande',
      'language': 'Idioma',
      'resetScore': 'Restablecer récord',
      'resetConfirm': '¿Borrar tu récord y estadísticas?',
      'cancel': 'Cancelar',
      'reset': 'Restablecer',
      'combo': 'Combo',
      'newBest': '¡Nuevo récord!',
      'noAds': 'Sin anuncios. Tus puntos se quedan en tu dispositivo.',
    },
  };

  String get(String key) => _values[code]?[key] ?? _values['en']![key] ?? key;
}
